### ISSUE TITLE
Can not run python manage.py migrate

### ISSUE THREAD

**Issue by npokasub** [saadmk11/banking-system#4]
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/narate/Python/Django/Banking/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/narate/Python/Django/Banking/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/Users/narate/Python/Django/Banking/env/lib/python3.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/Users/narate/Python/Django/Banking/env/lib/python3.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/narate/Python/Django/Banking/env/lib/python3.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/narate/Python/Django/Banking/banking-system/bankingsystem/__init__.py", line 5, in <module>
    from .celery import app as celery_app
  File "/Users/narate/Python/Django/Banking/banking-system/bankingsystem/celery.py", line 3, in <module>
    from celery import Celery
  File "<frozen importlib._bootstrap>", line 1032, in _handle_fromlist
  File "/Users/narate/Python/Django/Banking/env/lib/python3.7/site-packages/celery/local.py", line 509, in __getattr__
    module = __import__(self._object_origins[name], None, None, [name])
  File "/Users/narate/Python/Django/Banking/env/lib/python3.7/site-packages/celery/app/__init__.py", line 5, in <module>
    from celery import _state
  File "/Users/narate/Python/Django/Banking/env/lib/python3.7/site-packages/celery/_state.py", line 15, in <module>
    from celery.utils.threads import LocalStack
  File "/Users/narate/Python/Django/Banking/env/lib/python3.7/site-packages/celery/utils/__init__.py", line 10, in <module>
    from .nodenames import worker_direct, nodename, nodesplit
  File "/Users/narate/Python/Django/Banking/env/lib/python3.7/site-packages/celery/utils/nodenames.py", line 7, in <module>
    from kombu.entity import Exchange, Queue
  File "/Users/narate/Python/Django/Banking/env/lib/python3.7/site-packages/kombu/entity.py", line 6, in <module>
    from .abstract import MaybeChannelBound, Object
  File "/Users/narate/Python/Django/Banking/env/lib/python3.7/site-packages/kombu/abstract.py", line 6, in <module>
    from .connection import maybe_channel
  File "/Users/narate/Python/Django/Banking/env/lib/python3.7/site-packages/kombu/connection.py", line 893
    return self.transport.implements.async
                                         ^
SyntaxError: invalid syntax

**Comment by saadmk11** [comment]
You should use python version 3.6.x
